// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://berurlhqaulturltwrkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcnVybGhxYXVsdHVybHR3cmt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDEyMzksImV4cCI6MjA2NzcxNzIzOX0.EFhrDjuTocpFp7e_GLcrf-AAlZodqySWP3-AFAX_QoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});